[package]
name = "linkerd2-strategy"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
edition = "2018"
publish = false

# [features]
# rustfmt = ["linkerd2-proxy-api/rustfmt"]

[dependencies]
bytes = "0.5"
futures = "0.3"
http = "0.2"
http-body = "0.3"
indexmap = "1.0"
linkerd2-addr = { path  = "../addr" }
linkerd2-dns = { path  = "../dns" }
linkerd2-error = { path  = "../error" }
linkerd2-identity = { path  = "../identity" }
linkerd2-proxy-core = { path = "../proxy/core" }
linkerd2-proxy-api = { git = "https://github.com/linkerd/linkerd2-proxy-api", tag = "v0.1.13" }
linkerd2-service-profiles = { path  = "../service-profiles" }
linkerd2-stack = { path  = "../stack" }
rand = { version = "0.7" }
regex = "1.0.0"
tokio = { version = "0.2", features = ["macros", "sync", "time"] }
tonic = { version = "0.2", default-features = false }
tracing = "0.1.9"
tracing-futures = { version = "0.2", features = ["std-future"] }
pin-project = "0.4"

[dependencies.tower]
version = "0.3"
# disable tower's tracing `log` integration for performance reasons, since we
# will consume tower's traces as traces.
default-features = false
features = [
    "util",
    "retry",
]

[dev-dependencies]
linkerd2-proxy-api = { git = "https://github.com/linkerd/linkerd2-proxy-api", tag = "v0.1.13", features = ["arbitrary"] }
prost-types = "0.6.0"
quickcheck = { version = "0.9", default-features = false }
